# Setup
title:               NOPOR
tagline:             ''
description:         ''
url:                 https://projekt-nopor.github.io/spletna-stran
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
